obj-y += translate.o dsp_helper.o op_helper.o lmi_helper.o helper.o cpu.o
obj-y += gdbstub.o msa_helper.o mips-semi.o
obj-$(CONFIG_SOFTMMU) += machine.o
obj-$(CONFIG_KVM) += kvm.o

ifdef CONFIG_LLVM_HELPERS
bc-y += helper.bc dsp_helper.bc op_helper.bc lmi_helper.bc msa_helper.bc
endif
