obj-y = fpa11.o fpa11_cpdo.o fpa11_cpdt.o fpa11_cprt.o fpopcode.o
obj-y += single_cpdo.o double_cpdo.o extended_cpdo.o

ifdef CONFIG_LLVM_HELPERS
ll-y += fpa11.ll fpa11_cpdo.ll fpa11_cpdt.ll fpa11_cprt.ll fpopcode.ll
ll-y += single_cpdo.ll double_cpdo.ll extended_cpdo.ll
endif